# Generated by Django 5.2.17 on 2026-08-31 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaiTro',
            fields=[
                ('ma_vai_tro', models.BigAutoField(primary_key=True, serialize=False)),
                ('ten_vai_tro', models.CharField(max_length=50, unique=True, verbose_name='Tên vai trò')),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Vai trò',
                'verbose_name_plural': 'Danh mục Vai trò',
                'db_table': 'VaiTro',
            },
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('ma_nguoi_dung', models.BigAutoField(primary_key=True, serialize=False)),
                ('ten_dang_nhap', models.CharField(max_length=50, unique=True, verbose_name='Tên đăng nhập')),
                ('mat_khau', models.CharField(max_length=255, verbose_name='Mật khẩu (Hash)')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('trang_thai', models.CharField(choices=[('Hoạt động', 'Hoạt động'), ('Khóa', 'Khóa'), ('Tạm nghỉ', 'Tạm nghỉ')], default='Hoạt động', max_length=20, verbose_name='Trạng thái')),
                ('ca_lam_viec', models.CharField(default='Ca hành chính (8h–17h) • Tất cả khu', max_length=100, verbose_name='Ca làm việc')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('vai_tro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nguoi_dung_list', to='users.vaitro', verbose_name='Vai trò')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Danh sách Người dùng',
                'db_table': 'NguoiDung',
            },
        ),
    ]
