# Generated by Django 5.2.17 on 2026-10-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hoạt động gần nhất'),
        ),
    ]
