# Generated by Django 5.2.17 on 2026-08-31 15:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhuVuc',
            fields=[
                ('ma_khu_vuc', models.BigAutoField(primary_key=True, serialize=False)),
                ('ten_khu_vuc', models.CharField(max_length=20, unique=True, verbose_name='Tên khu vực')),
                ('suc_chua_toi_da', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sức chứa tối đa')),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Khu vực đỗ xe',
                'verbose_name_plural': 'Danh mục Khu vực đỗ xe',
                'db_table': 'KhuVuc',
            },
        ),
        migrations.CreateModel(
            name='BangGia',
            fields=[
                ('ma_bang_gia', models.BigAutoField(primary_key=True, serialize=False)),
                ('loai_ap_dung', models.CharField(choices=[('VeLuot', 'Vé lượt'), ('VeThang', 'Vé tháng')], default='VeLuot', max_length=20, verbose_name='Loại áp dụng')),
                ('gia_co_ban', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá cơ bản (VNĐ)')),
                ('don_vi_thoi_gian_phut', models.IntegerField(default=60, verbose_name='Đơn vị tính (phút)')),
                ('gia_tang_them', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Giá tăng thêm mỗi chu kỳ (VNĐ)')),
                ('gia_ban_dem', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Phụ phí ban đêm (VNĐ)')),
                ('ngay_ap_dung', models.DateTimeField(auto_now_add=True, verbose_name='Ngày áp dụng')),
                ('loai_xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bang_gia_list', to='vehicles.loaixe', verbose_name='Loại xe')),
            ],
            options={
                'verbose_name': 'Bảng giá',
                'verbose_name_plural': 'Bảng giá tính phí',
                'db_table': 'BangGia',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('ma_vi_tri', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã vị trí')),
                ('area', models.CharField(blank=True, max_length=80, verbose_name='Khu vực (text)')),
                ('status', models.CharField(choices=[('available', 'Trống'), ('occupied', 'Đang đỗ'), ('maintenance', 'Bảo trì')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('khu_vuc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parking.khuvuc', verbose_name='Khu vực')),
            ],
            options={
                'verbose_name': 'Vị trí đỗ xe',
                'verbose_name_plural': 'Danh sách Vị trí đỗ xe',
                'db_table': 'ViTriDo',
            },
        ),
    ]
