# Generated by Django 5.2.17 on 2026-08-31 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiXe',
            fields=[
                ('ma_loai_xe', models.BigAutoField(primary_key=True, serialize=False)),
                ('ten_loai_xe', models.CharField(max_length=50, unique=True, verbose_name='Tên loại xe')),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Loại xe',
                'verbose_name_plural': 'Danh mục Loại xe',
                'db_table': 'LoaiXe',
            },
        ),
        migrations.CreateModel(
            name='PhuongTien',
            fields=[
                ('ma_phuong_tien', models.BigAutoField(primary_key=True, serialize=False)),
                ('bien_so_xe', models.CharField(max_length=20, verbose_name='Biển số xe')),
                ('mau_xe', models.CharField(blank=True, max_length=50, null=True, verbose_name='Màu xe')),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả')),
                ('loai_xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phuong_tien_list', to='vehicles.loaixe', verbose_name='Loại xe')),
            ],
            options={
                'verbose_name': 'Phương tiện',
                'verbose_name_plural': 'Danh sách Phương tiện',
                'db_table': 'PhuongTien',
            },
        ),
    ]
