# Generated by Django 5.2.17 on 2026-08-31 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCaoThongKe',
            fields=[
                ('ma_bao_cao', models.BigAutoField(primary_key=True, serialize=False)),
                ('loai_bao_cao', models.CharField(choices=[('Ngay', 'Theo ngày'), ('Tuan', 'Theo tuần'), ('Thang', 'Theo tháng')], max_length=20, verbose_name='Loại báo cáo')),
                ('ngay_bat_dau', models.DateField(verbose_name='Ngày bắt đầu')),
                ('ngay_ket_thuc', models.DateField(verbose_name='Ngày kết thúc')),
                ('tong_luot_xe', models.IntegerField(default=0, verbose_name='Tổng lượt xe')),
                ('tong_doanh_thu', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Tổng doanh thu (VNĐ)')),
                ('ty_le_lap_day_trung_binh', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tỷ lệ lấp đầy (%)')),
                ('khung_gio_cao_diem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Khung giờ cao điểm')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tổng hợp')),
                ('khu_vuc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.khuvuc', verbose_name='Khu vực')),
            ],
            options={
                'verbose_name': 'Báo cáo thống kê',
                'verbose_name_plural': 'Dữ liệu Báo cáo & Thống kê',
                'db_table': 'BaoCaoThongKe',
            },
        ),
    ]
