# Generated by Django 5.2.17 on 2026-08-31 15:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        ('users', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeXe',
            fields=[
                ('ma_ve', models.BigAutoField(primary_key=True, serialize=False)),
                ('ma_dinh_danh_the', models.CharField(max_length=50, unique=True, verbose_name='Mã định danh thẻ (RFID)')),
                ('loai_the', models.CharField(choices=[('Vé lượt', 'Vé lượt'), ('Vé tháng', 'Vé tháng')], default='Vé lượt', max_length=20, verbose_name='Loại thẻ')),
                ('trang_thai_the', models.CharField(choices=[('Sẵn sàng', 'Sẵn sàng'), ('Đang gửi', 'Đang gửi'), ('Khóa', 'Khóa'), ('Hỏng', 'Hỏng')], default='Sẵn sàng', max_length=20, verbose_name='Trạng thái thẻ')),
            ],
            options={
                'verbose_name': 'Vé xe',
                'verbose_name_plural': 'Danh mục Vé xe',
                'db_table': 'VeXe',
            },
        ),
        migrations.CreateModel(
            name='VeThang',
            fields=[
                ('ma_ve_thang', models.BigAutoField(primary_key=True, serialize=False)),
                ('ho_ten_khach_hang', models.CharField(max_length=100, verbose_name='Họ tên khách hàng')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('ngay_bat_dau', models.DateField(verbose_name='Ngày bắt đầu')),
                ('ngay_ket_thuc', models.DateField(verbose_name='Ngày kết thúc')),
                ('moi_gia_han', models.BooleanField(default=True, verbose_name='Mới gia hạn')),
                ('trang_thai_ve', models.CharField(choices=[('Còn hiệu lực', 'Còn hiệu lực'), ('Đã hết hạn', 'Đã hết hạn'), ('Sắp hết hạn', 'Sắp hết hạn')], default='Còn hiệu lực', max_length=20, verbose_name='Trạng thái vé')),
                ('phuong_tien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ve_thang_list', to='vehicles.phuongtien', verbose_name='Phương tiện')),
                ('the_xe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ve_thang_list', to='tickets.vexe', verbose_name='Thẻ xe')),
            ],
            options={
                'verbose_name': 'Vé tháng',
                'verbose_name_plural': 'Danh sách Vé tháng',
                'db_table': 'VeThang',
            },
        ),
        migrations.CreateModel(
            name='LuotGuiXe',
            fields=[
                ('ma_luot_gui', models.BigAutoField(primary_key=True, serialize=False)),
                ('bien_so_xe_kiem_tra', models.CharField(max_length=20, verbose_name='Biển số xe')),
                ('thoi_gian_vao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian vào')),
                ('thoi_gian_ra', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian ra')),
                ('tong_tien_phi', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng tiền phí (VNĐ)')),
                ('trang_thai_luot', models.CharField(choices=[('Đang gửi', 'Đang gửi'), ('Đã ra', 'Đã ra')], default='Đang gửi', max_length=20, verbose_name='Trạng thái lượt')),
                ('khu_vuc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='luot_gui_list', to='parking.khuvuc', verbose_name='Khu vực')),
                ('loai_xe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicles.loaixe', verbose_name='Loại xe')),
                ('nguoi_dung_ra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='luot_ra_list', to='users.nguoidung', verbose_name='Nhân viên ghi nhận ra')),
                ('nguoi_dung_vao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='luot_vao_list', to='users.nguoidung', verbose_name='Nhân viên ghi nhận vào')),
                ('phuong_tien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='luot_gui_list', to='vehicles.phuongtien', verbose_name='Phương tiện')),
                ('vi_tri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='luot_gui_list', to='parking.parkingspot', verbose_name='Vị trí đỗ')),
                ('ve_xe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='luot_gui_list', to='tickets.vexe', verbose_name='Vé xe')),
            ],
            options={
                'verbose_name': 'Lượt gửi xe',
                'verbose_name_plural': 'Danh sách Lượt gửi xe',
                'db_table': 'LuotGuiXe',
                'constraints': [models.CheckConstraint(condition=models.Q(('thoi_gian_ra__isnull', True), ('thoi_gian_ra__gte', models.F('thoi_gian_vao')), _connector='OR'), name='chk_thoi_gian_hop_le')],
            },
        ),
    ]
