# Generated by Django 5.2.17 on 2026-10-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vethang',
            name='the_xe',
        ),
        migrations.RemoveField(
            model_name='luotguixe',
            name='ve_xe',
        ),
        migrations.DeleteModel(
            name='VeXe',
        ),
    ]
